//! Axum router composition.

pub mod dto;
pub mod embeddings;
pub mod health;
pub mod metrics;
pub mod tei;

use crate::{
    auth::{ApiKeyAuth, require_api_key},
    routes::{
        dto::{
            EmbeddingObject, EmbeddingRequest, EmbeddingResponse, EmbeddingVector, ErrorResponse,
            HealthModelStatus, HealthStatus, ModelInfo, ModelsListResponse, OpenAiModelInfo,
            TeiEmbedRequest, Usage,
        },
        embeddings::{
            __path_create_embeddings, __path_list_models, create_embeddings, list_models,
        },
        health::{__path_health, __path_ready, health, ready},
        metrics::{__path_metrics, metrics},
        tei::{
            __path_tei_embed, __path_tei_info, __path_tei_per_model_embed,
            __path_tei_per_model_info, tei_embed, tei_info, tei_per_model_embed,
            tei_per_model_info,
        },
    },
    state::AppState,
    telemetry::request_tracing_middleware,
};
use axum::{
    Router,
    http::StatusCode,
    middleware,
    routing::{get, post},
};
use std::sync::Arc;
use tower_http::{
    compression::CompressionLayer, cors::CorsLayer, timeout::TimeoutLayer, trace::TraceLayer,
};
use utoipa::OpenApi;
use utoipa_scalar::{Scalar, Servable};

/// API documentation generated by utoipa.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "model2vec-serve",
        version = "0.5.0",
        description = "OpenAI and TEI compatible embeddings server"
    ),
    paths(
        create_embeddings,
        list_models,
        tei_embed,
        tei_per_model_embed,
        tei_info,
        tei_per_model_info,
        health,
        ready,
        metrics
    ),
    components(schemas(
        EmbeddingRequest,
        EmbeddingObject,
        EmbeddingResponse,
        EmbeddingVector,
        Usage,
        ErrorResponse,
        TeiEmbedRequest,
        ModelInfo,
        OpenAiModelInfo,
        ModelsListResponse,
        HealthModelStatus,
        HealthStatus
    ))
)]
pub struct ApiDoc;

/// Build the application router.
pub fn app(state: Arc<AppState>) -> Router {
    let api = Router::new()
        .route("/v1/embeddings", post(create_embeddings))
        .route("/v1/models", get(list_models))
        .route("/embed", post(tei_embed))
        .route("/tei/{model_id}/embed", post(tei_per_model_embed))
        .route("/tei/{model_id}/info", get(tei_per_model_info))
        .route("/info", get(tei_info));

    let protected = if let Some(ref key) = state.config.api_key {
        api.layer(middleware::from_fn_with_state(
            ApiKeyAuth::new(key.clone()),
            require_api_key,
        ))
    } else {
        api
    };

    Router::new()
        .merge(protected)
        .route("/health", get(health))
        .route("/ready", get(ready))
        .route("/metrics", get(metrics))
        .merge(Scalar::with_url("/docs", ApiDoc::openapi()))
        .layer(
            tower::ServiceBuilder::new()
                .layer(TraceLayer::new_for_http())
                .layer(TimeoutLayer::with_status_code(
                    StatusCode::REQUEST_TIMEOUT,
                    std::time::Duration::from_secs(state.config.request_timeout_seconds),
                ))
                .layer(CorsLayer::permissive())
                .layer(CompressionLayer::new())
                .layer(middleware::from_fn(request_tracing_middleware)),
        )
        .with_state(state)
}
