apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model2vec-serve.fullname" . }}
  labels:
    {{- include "model2vec-serve.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "model2vec-serve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "model2vec-serve.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --model
            - {{ .Values.model | quote }}
            {{- if .Values.apiKey }}
            - --api-key
            - $(API_KEY)
            {{- end }}
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "model2vec-serve.fullname" . }}
                  key: api-key
                  optional: true
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
