{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model2vec-serve.fullname" . }}
  labels:
    {{- include "model2vec-serve.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey | quote }}
{{- end }}
